config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get "/customers/all" => 'customers#index_all', :as => 'customers_all'
  resources :admins
  resources :customers do
    collection do
      get 'set_init_date'
    end
  end
  resources :petros
  resources :fuels
  resources :calls
  resources :employees
  resources :stations
  get "/petros/:id/calltimes" => 'calltimes#new', :as => 'calltimes'
  get "/customer/search" => 'customers#search_customer', :as => 'search_customer'
  post "/customer/search" => 'customers#search', :as => 'searched_customer'
  post "/petros/:id/calltimes" => 'calltimes#create', :as => 'create_calltimes'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_one :station
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calltime.rb
class Calltime < ApplicationRecord
  belongs_to :petro
end

app/models/customer.rb
class Customer < ApplicationRecord
  enum type_customer: ['Thường xuyên', 'Không thường xuyên']
  has_many :petros, -> { order "day_fuel DESC" }, :dependent => :destroy
  has_many :day_fuel_petros, :dependent => :destroy, class_name: 'Petro'
  has_one :petro, -> { order "id DESC" }, class_name: 'Petro'
  accepts_nested_attributes_for :day_fuel_petros, :allow_destroy => true
  
  validates :name, 
    length: { 
      in: 4..30,
      too_short: "Tên nhập quá ngắn, phải có ít nhất 4 kí tự trở lên.",
      too_long: "Tên nhập quá dài, dưới 30 kí tự." }

  validates :phone, 
    length: { 
      in: 9..12,
      too_short: "SĐT nhập quá ngắn, phải có ít nhất 9 kí tự trở lên.",
      too_long: "SĐT nhập quá dài, dưới 12 kí tự."},
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập các kí tự là số" }

  validates :car_number, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  validates :name, presence: { message: "Yêu cầu nhập tên của nhiên liệu" }
  validates :price, 
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập giá tiền là số" }
end

app/models/petro.rb
class Petro < ApplicationRecord
  has_many :calltimes
  belongs_to :customer

  after_save :update_customer

  private
    def update_customer
      customer = self.customer
      customer.update(last_date_petro: customer.petros[0].day_fuel)
    end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_params, only: [:edit, :show, :update, :destroy]

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save 
      flash[:success] = 'Admin đã được tạo.'
      redirect_to admins_path
    else
      render :new 
    end
  end

  def index
    @admins = Admin.all
  end

  # def show
  #   @petro = Petro.new
  #   @petros = Petro.where(customer_id: params[:id]).order(day_fuel: 'desc')
  #   @fuels = Fuel.all
  # end
  
  def edit
  end

  def update
    if @admin.update(admin_params)
      flash[:success] = 'Admin đã được cập nhật.'
      redirect_to edit_admin_path(@admin) 
    else
      render :edit
    end
  end

  def destroy
    @admin.destroy
    flash[:error] = 'Nhân viên đã được xóa..'
    redirect_to employees_path
  end

  private
  def set_params
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:name, :user_name, :email, :phone, :role, :password, :avatar) 
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def index
    # @usually_customers = Petro.joins(:customer).where("type_customer = 0").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Petro.joins(:customer).where("type_customer = 1").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])

    usually_customers_ids = Petro.where("day_fuel > ?", 5.days.ago).pluck(:customer_id).uniq
    @usually_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 0").where.not(id: usually_customers_ids).order("petros.day_fuel DESC").page(params[:page])
    rarely_customers_ids = Petro.where("day_fuel > ?", 15.days.ago).pluck(:customer_id).uniq
    @rarely_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 1").where.not(id: rarely_customers_ids).order("petros.day_fuel DESC").page(params[:page_rare])


    # @usually_customers = Customer.where(type_customer: 0).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Customer.where(type_customer: 1).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])
    # binding.pry
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_params, only: [:edit, :show, :update, :destroy]

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save 
      flash[:success] = 'Nhân viên đã được tạo.'
      redirect_to employees_path 
    else
      render :new 
    end
  end

  def index
    @employees = Employee.all
  end

  # def show
  #   @petro = Petro.new
  #   @petros = Petro.where(customer_id: params[:id]).order(day_fuel: 'desc')
  #   @fuels = Fuel.all
  # end
  
  def edit
  end

  def update
    if @@employee.update(employee_params)
      flash[:success] = 'Nhân viên đã được cập nhật.'
      redirect_to @employees
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy
    flash[:error] = 'Nhân viên đã được xóa.'
    redirect_to employees_path
  end

  private
  def set_params
    @employee = Employee.find(params[:id])
  end

  def employee_params
  	params.require(:employee).permit(:name,:phone, :address, :gender, :department, :position, :slary) 
  end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  def new
    @fuel = Fuel.new
  end

  def index
    @fuels = Fuel.all
  end

  def create
    @fuel = Fuel.new(fuel_params)
    if @fuel.save
        flash[:success] = 'Tạo nhiên liệu thành công.'
        redirect_to fuels_path
    else
        flash[:alert] = @fuel.errors.full_messages.join('  ;  ')
        render :new
    end
  end

  def edit
    @fuel = Fuel.find(params[:id])
  end
  
  def update
    @fuel = Fuel.find(params[:id])
    if @fuel.update(fuel_params)
      flash[:success] = 'Nội dung giao dịch đã được sửa'
      redirect_to fuels_path
    else
      render :edit
    end
  end

  def destroy
    @fuel = Fuel.find(params[:id])
    @fuel.destroy
    flash[:error] = 'Nhiên liệu đã được xóa.'
    redirect_to fuels_path
  end

  private
  def fuel_params
  	params.require(:fuel).permit(:name, :price) 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def convert_money(price)
    return price.to_s[0..-3].reverse!.scan(/.{1,3}/).join(',').reverse!
  end
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/calltimes_helper.rb
module CalltimesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/petros_helper.rb
module PetrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:error] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/employees/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Sửa thông tin nhân viên</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Thêm khách hàng <small>những khách hàng mới hoàn toàn</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @employee, url: employees_path, method: 'POST', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Họ và Tên<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">SĐT<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Địa chỉ nhà</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :address, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Phòng ban
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :department, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Chức vụ
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :position, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Giới tính</label>
              <div class="checkbox col-md-2 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :gender, 0, :checked => true, class: 'flat' %> Nam
                </label>
              </div>
              <div class="checkbox col-md-3 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :gender, 1, :checked => false, class: 'flat' %> Nữ
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Lương hiện tại
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :salary, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Xóa nhân viên này', employee_path(@employee), :class => 'btn btn-danger', :method => :delete, data: {:confirm => "Bạn có chắc là muốn xóa nhân viên này?" } %>
                <%= f.submit 'Sửa thông tin', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Danh sách nhân viên</h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Danh sách toàn bộ thông tin của  nhân viên</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-buttons1" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Tên nhân viên</th>
              <th>SĐT</th>
              <th>Địa chỉ nhà</th>
              <th>Chức vụ - Phòng ban</th>
              <th>Tác vụ</th>
            </tr>
          </thead>

          <tbody>
            <% @employees.each do |em| %>
              <tr>
                <td><%= em.name %></td>
                <td><%= em.phone %></td>
                <td><%= em.address %></td>
                <td><%= em.position %> - <%= em.department %></td>
                <td>
                  <%= link_to "Xóa", employee_path(em), :class => 'btn btn-danger', method: :delete, data: {:confirm => "Bạn có chắc là muốn xóa nhân viên này?" } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Thêm nhân viên mới</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Thêm nhân viên<small>người làm việc cho doanh nghiệp của bạn</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @employee, url: employees_path, method: 'POST', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Họ và Tên<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">SĐT<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Địa chỉ nhà</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :address, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Phòng ban
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :department, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Chức vụ
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :position, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Giới tính</label>
              <div class="checkbox col-md-2 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :gender, 0, :checked => true, class: 'flat' %> Nam
                </label>
              </div>
              <div class="checkbox col-md-3 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :gender, 1, :checked => false, class: 'flat' %> Nữ
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Lương hiện tại
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :salary, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Hủy bỏ', customers_path,  { :class => 'btn btn-primary' } %>
                <%= f.submit 'Tạo nhân viên mới', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>