config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get "/customers/all" => 'customers#index_all', :as => 'customers_all'
  resources :admins
  resources :customers do
    collection do
      get 'set_init_date'
    end
  end
  resources :petros
  resources :fuels
  resources :calls
  resources :employees
  resources :stations
  get "/petros/:id/calltimes" => 'calltimes#new', :as => 'calltimes'
  get "/customer/search" => 'customers#search_customer', :as => 'search_customer'
  post "/customer/search" => 'customers#search', :as => 'searched_customer'
  post "/petros/:id/calltimes" => 'calltimes#create', :as => 'create_calltimes'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_one :station
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calltime.rb
class Calltime < ApplicationRecord
  belongs_to :petro
end

app/models/customer.rb
class Customer < ApplicationRecord
  enum type_customer: ['Thường xuyên', 'Không thường xuyên']
  has_many :petros, -> { order "day_fuel DESC" }, :dependent => :destroy
  has_many :day_fuel_petros, :dependent => :destroy, class_name: 'Petro'
  has_one :petro, -> { order "id DESC" }, class_name: 'Petro'
  accepts_nested_attributes_for :day_fuel_petros, :allow_destroy => true
  
  validates :name, 
    length: { 
      in: 4..30,
      too_short: "Tên nhập quá ngắn, phải có ít nhất 4 kí tự trở lên.",
      too_long: "Tên nhập quá dài, dưới 30 kí tự." }

  validates :phone, 
    length: { 
      in: 9..12,
      too_short: "SĐT nhập quá ngắn, phải có ít nhất 9 kí tự trở lên.",
      too_long: "SĐT nhập quá dài, dưới 12 kí tự."},
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập các kí tự là số" }

  validates :car_number, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  validates :name, presence: { message: "Yêu cầu nhập tên của nhiên liệu" }
  validates :price, 
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập giá tiền là số" }
end

app/models/petro.rb
class Petro < ApplicationRecord
  has_many :calltimes
  belongs_to :customer

  after_save :update_customer

  private
    def update_customer
      customer = self.customer
      customer.update(last_date_petro: customer.petros[0].day_fuel)
    end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :admin
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def index
    # @usually_customers = Petro.joins(:customer).where("type_customer = 0").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Petro.joins(:customer).where("type_customer = 1").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])

    usually_customers_ids = Petro.where("day_fuel > ?", 5.days.ago).pluck(:customer_id).uniq
    @usually_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 0").where.not(id: usually_customers_ids).order("petros.day_fuel DESC").page(params[:page])
    rarely_customers_ids = Petro.where("day_fuel > ?", 15.days.ago).pluck(:customer_id).uniq
    @rarely_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 1").where.not(id: rarely_customers_ids).order("petros.day_fuel DESC").page(params[:page_rare])


    # @usually_customers = Customer.where(type_customer: 0).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Customer.where(type_customer: 1).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])
    # binding.pry
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def convert_money(price)
    return price.to_s[0..-3].reverse!.scan(/.{1,3}/).join(',').reverse!
  end
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/calltimes_helper.rb
module CalltimesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/petros_helper.rb
module PetrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:error] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/admins/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Sửa thông tin cá nhân</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @admin, url: admins_path, method: 'POST', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Họ và Tên<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">SĐT<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Email</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :email, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Mật khẩu
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.password_field :password, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Phân quyền</label>
              <div class="col-md-3 col-sm-3 col-xs-12">
                <select class="form-control">
                  <option>Chọn quyền</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Hủy bỏ', customers_path,  { :class => 'btn btn-primary' } %>
                <%= f.submit 'Tạo nhân viên mới', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Danh sách nhân viên</h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Danh sách toàn bộ thông tin của  nhân viên</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <table id="datatable-buttons1" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Tên nhân viên</th>
              <th>SĐT</th>
              <th>Email</th>
              <th>Quyền hạn</th>
              <th>Tác vụ</th>
            </tr>
          </thead>

          <tbody>
            <% @admins.each do |em| %>
              <tr>
                <td><%= em.name %></td>
                <td><%= em.phone %></td>
                <td><%= em.email %></td>
                <td><%= em.role %></td>
                <td>
                  <%= link_to "Sửa", edit_admin_path(em), :class => 'btn btn-warning' %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Thêm người quản lý</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @admin, url: admins_path, method: 'POST', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Họ và Tên<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">SĐT<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Email</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :email, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Mật khẩu
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.password_field :password, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Phân quyền</label>
              <div class="col-md-3 col-sm-3 col-xs-12">
                <select class="form-control">
                  <option>Chọn quyền</option>
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Hủy bỏ', customers_path,  { :class => 'btn btn-primary' } %>
                <%= f.submit 'Tạo nhân viên mới', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <title><%= yield :title %></title>
    <%= javascript_include_tag 'gen' %>
  </head>

  <% if logged_in? == true %>
    <body class="nav-md">
      <% flash.each do |name, msg|
        arr = msg.split('  ;  ')
        if arr.length > 0 %>
        <div class="<%= 'alert ' + alert_for(name)%>">
          <% arr.each do |item| %>
            <span style="margin-right: 20px">✦</span><%= item %> <br>
          <% end %>
        </div>
        <% else %>
          <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
        <% end %>
      <% end %>
      <div class="container body">
        <div class="main_container">
          <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
              <%= render partial: 'layouts/shared/leftnav' %>
            </div>
          </div>

          <!-- top navigation -->
          <div class="top_nav">
            <div class="nav_menu">
              <nav>
                <%= render partial: 'layouts/shared/topnav' %>
              </nav>
            </div>
          </div>
          <!-- /top navigation -->

          <!-- page content -->
          <div class="right_col" role="main">
            <%= yield %>
          </div>
          <!-- /page content -->

          <!-- footer content -->
          <footer>
            <%= render partial: 'layouts/shared/footer' %>
          </footer>
          <!-- /footer content -->
        </div>
      </div>
    <% else %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
      <body class="login">
        <%= yield %>
    <% end %>
  <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/kitchen.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'kitchen', media: 'all' %>
    <%= javascript_include_tag :modernizr %>

    <title>Bootstrap Kitchen Sink</title>

  </head>

  <body data-spy="scroll" data-target="#sidebar">
    <%= yield %>
    <%= javascript_include_tag 'kitchen' %>
  </body>
</html>

app/views/layouts/kitchen8.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tags %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'kitchen8', media: 'all' %>
    <%= javascript_include_tag :modernizr %>

    <title>Bootstrap Kitchen Sink</title>

  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'kitchen' %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div class="pull-right">
  Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <a href="index.html" class="site_title"><i class="fa fa-paw"></i> 
  <% if current_user.station %>
    <span><%= current_user.station.name %></span>
  <% end %>
  </a>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <img src="images/img.jpg" alt="..." class="img-circle profile_img">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2><%= current_user.name %></h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-home"></i>Trang Phân Tích<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <%# <li><a href="index.html">Dashboard</a></li>
          <li><a href="index2.html">Dashboard2</a></li>
          <li><a href="index3.html">Dashboard3</a></li> %>
        </ul>
      </li>
      <li><a><i class="fa fa-edit"></i>Khách hàng<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to 'Thêm, Tìm Khách Hàng', search_customer_path %></li>
          <li><%= link_to 'Danh Sách Khách Hàng', customers_path %></li>
          <li><%= link_to 'Kết Xuất Thông Tin', customers_all_path %></li>
        </ul>
      </li>
      <li><a><i class="fa fa-desktop"></i>Hoạt Động Khách Hàng<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
         <%# <li><a href="general_elements.html">Khách Hàng Tiêm Năng</a></li> %>
          <li><%= link_to 'Kêu Gọi Khách Hàng',calls_path %></li>
          <li><%= link_to 'Giao Dịch', petros_path %></li>
        </ul>
      </li>
      <%# <li><a><i class="fa fa-table"></i>Tình Hình Kinh Doanh<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="tables_dynamic.html">Đầu tư - Chi trả</a></li>
          <li><a href="tables.html">Nguồn Thu</a></li>
        </ul> %>
      </li>
    </ul>
  </div>
  <div class="menu_section">
    <h3>Phần Quản Lý Doanh Nghiệp</h3>
    <ul class="nav side-menu">
      <li>
        <%= link_to 'Thông Tin DN', edit_station_path(current_user.station) %>
      </li>
      <li>
        <%= link_to 'Thông Tin Cá Nhân', edit_admin_path(current_user.id) %>
      </li>
      <li><a><i class="fa fa-windows"></i>Quản Lý Nhiên Liệu <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to 'Thêm Nhiên Liệu', new_fuel_path %></li>
          <li><%= link_to 'Danh Sách Nhiên Liệu', fuels_path %></li>
        </ul>
      </li>
      <li><a><i class="fa fa-windows"></i>Nhân Viên <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to 'Thêm Nhân Viên', new_employee_path %></li>
          <li><%= link_to 'Danh Sách Nhân Viên', employees_path %></li>
        </ul>
      </li>
      <li><a><i class="fa fa-windows"></i>Phân Quyền Quản lý<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><%= link_to 'Thêm Quản Lý', new_admin_path %></li>
          <li><%= link_to 'Danh Sách Quản Lý', admins_path %></li>
        </ul>
      </li>
    </ul>
  </div>

</div>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <%= link_to logout_path, method: :delete do %>
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  <% end %>
</div>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <a id="menu_toggle"><i class="fa fa-bars"></i></a>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <img src="images/img.jpg" alt=""><%= current_user.name %>
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li><a href="javascript:;"> Profile</a></li>
      <li>
        <a href="javascript:;">
          <span class="badge bg-red pull-right">50%</span>
          <span>Settings</span>
        </a>
      </li>
      <li><a href="javascript:;">Help</a></li>
      <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
    </ul>
  </li>

  <li role="presentation" class="dropdown">
    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
      <i class="fa fa-envelope-o"></i>
      <span class="badge bg-green">6</span>
    </a>
    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <a>
          <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
          <span>
            <span>John Smith</span>
            <span class="time">3 mins ago</span>
          </span>
          <span class="message">
            Film festivals used to be do-or-die moments for movie makers. They were where...
          </span>
        </a>
      </li>
      <li>
        <div class="text-center">
          <a>
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </div>
      </li>
    </ul>
  </li>
</ul>