config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get "/customers/all" => 'customers#index_all', :as => 'customers_all'
  resources :admins
  resources :customers do
    collection do
      get 'set_init_date'
    end
  end
  resources :petros
  resources :fuels
  resources :calls
  resources :employees
  resources :stations
  get "/petros/:id/calltimes" => 'calltimes#new', :as => 'calltimes'
  get "/customer/search" => 'customers#search_customer', :as => 'search_customer'
  post "/customer/search" => 'customers#search', :as => 'searched_customer'
  post "/petros/:id/calltimes" => 'calltimes#create', :as => 'create_calltimes'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  has_one :station
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calltime.rb
class Calltime < ApplicationRecord
  belongs_to :petro
end

app/models/customer.rb
class Customer < ApplicationRecord
  enum type_customer: ['Thường xuyên', 'Không thường xuyên']
  has_many :petros, -> { order "day_fuel DESC" }, :dependent => :destroy
  has_many :day_fuel_petros, :dependent => :destroy, class_name: 'Petro'
  has_one :petro, -> { order "id DESC" }, class_name: 'Petro'
  accepts_nested_attributes_for :day_fuel_petros, :allow_destroy => true
  
  validates :name, 
    length: { 
      in: 4..30,
      too_short: "Tên nhập quá ngắn, phải có ít nhất 4 kí tự trở lên.",
      too_long: "Tên nhập quá dài, dưới 30 kí tự." }

  validates :phone, 
    length: { 
      in: 9..12,
      too_short: "SĐT nhập quá ngắn, phải có ít nhất 9 kí tự trở lên.",
      too_long: "SĐT nhập quá dài, dưới 12 kí tự."},
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập các kí tự là số" }

  validates :car_number, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/fuel.rb
class Fuel < ApplicationRecord
  validates :name, presence: { message: "Yêu cầu nhập tên của nhiên liệu" }
  validates :price, 
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập giá tiền là số" }
end

app/models/petro.rb
class Petro < ApplicationRecord
  has_many :calltimes
  belongs_to :customer

  after_save :update_customer

  private
    def update_customer
      customer = self.customer
      customer.update(last_date_petro: customer.petros[0].day_fuel)
    end
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_params, only: [:edit, :show, :update, :destroy]

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save 
      flash[:success] = 'Admin đã được tạo.'
      redirect_to admins_path
    else
      render :new 
    end
  end

  def index
    @admins = Admin.all
  end

  # def show
  #   @petro = Petro.new
  #   @petros = Petro.where(customer_id: params[:id]).order(day_fuel: 'desc')
  #   @fuels = Fuel.all
  # end
  
  def edit
  end

  def update
    if @admin.update(admin_params)
      flash[:success] = 'Admin đã được cập nhật.'
      redirect_to edit_admin_path(@admin) 
    else
      render :edit
    end
  end

  def destroy
    @admin.destroy
    flash[:error] = 'Nhân viên đã được xóa..'
    redirect_to employees_path
  end

  private
  def set_params
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:name, :user_name, :email, :phone, :role, :password, :avatar) 
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def index
    # @usually_customers = Petro.joins(:customer).where("type_customer = 0").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Petro.joins(:customer).where("type_customer = 1").where.not(customer_id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])

    usually_customers_ids = Petro.where("day_fuel > ?", 5.days.ago).pluck(:customer_id).uniq
    @usually_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 0").where.not(id: usually_customers_ids).order("petros.day_fuel DESC").page(params[:page])
    rarely_customers_ids = Petro.where("day_fuel > ?", 15.days.ago).pluck(:customer_id).uniq
    @rarely_customers = Customer.includes(petro: [:calltimes]).where("type_customer = 1").where.not(id: rarely_customers_ids).order("petros.day_fuel DESC").page(params[:page_rare])


    # @usually_customers = Customer.where(type_customer: 0).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 5.days.ago).ids])
    # @rarely_customers = Customer.where(type_customer: 1).where.not(id: [Customer.joins(:petros).where("petros.day_fuel > ?", 15.days.ago).ids])
    # binding.pry
  end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  def new
    @fuel = Fuel.new
  end

  def index
    @fuels = Fuel.all
  end

  def create
    @fuel = Fuel.new(fuel_params)
    if @fuel.save
        flash[:success] = 'Tạo nhiên liệu thành công.'
        redirect_to fuels_path
    else
        flash[:alert] = @fuel.errors.full_messages.join('  ;  ')
        render :new
    end
  end

  def edit
    @fuel = Fuel.find(params[:id])
  end
  
  def update
    @fuel = Fuel.find(params[:id])
    if @fuel.update(fuel_params)
      flash[:success] = 'Nội dung giao dịch đã được sửa'
      redirect_to fuels_path
    else
      render :edit
    end
  end

  def destroy
    @fuel = Fuel.find(params[:id])
    @fuel.destroy
    flash[:error] = 'Nhiên liệu đã được xóa.'
    redirect_to fuels_path
  end

  private
  def fuel_params
  	params.require(:fuel).permit(:name, :price) 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def convert_money(price)
    return price.to_s[0..-3].reverse!.scan(/.{1,3}/).join(',').reverse!
  end
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/helpers/calltimes_helper.rb
module CalltimesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/petros_helper.rb
module PetrosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in user
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete :user_id
  end

  def current_user
    return unless session[:user_id]
    if(Admin.find(session[:user_id])!=nil)
   	  @current_user ||= Admin.find(session[:user_id])
   	else
   		log_out
   	  redirect_to login_path
   	end
  end
 def logged_in?
    !current_user.nil?
  end

   # Confirms a logged-in user.
  # def user_signed_in?
  #   unless logged_in?
  #     flash[:error] = "Please log in."
  #     redirect_to login_path
  #   end
  # end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/calls/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Kêu gọi khách hàng<small>Những khách hàng đã quá chu kì mà chưa thực hiện giao dịch lại.</small></h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Danh sách các khách hàng "Loại Thường Xuyên"</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
       Tập hợp danh sách tất cả các khách hàng <code>Thường Xuyên</code> của bạn, là những khách hàng có chu kì đổ nhiên liệu trong phạm vi<code>5 ngày</code>.<br>
        </p>
        <table id="datatable-buttons1" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Tên</th>
              <th>Biển số xe</th>
              <th>SĐT</th>
              <th>Loại khách hàng</th>
              <th>Giao dịch gần nhất</th>
              <th>Thuộc công ty</th>
              <th>Thực hiện cuộc gọi</th>
              <th>Tác vụ</th>
            </tr>
          </thead>

          <tbody>
            <% @usually_customers.each do |customer| %>
              <tr>
                <td><%= customer.name %></td>
                <td><%= customer.car_number %></td>
                <td><%= customer.phone %></td>
                <td><%= customer.type_customer %></td>
                <td><%= customer.petro.day_fuel.strftime('%d/%m/%Y') %></td>
                <td><%= customer.company %></td>
                <% if customer.petro.calltimes.length > 0 %>
                  <td style="background-color: #60a917; color: white">Đã thực hiện <span><%= customer.petro.calltimes.length %></span> cuộc gọi</td>
                <% else %>
                  <td> chưa thực hiện cuộc gọi nào</td>
                <% end %>
                <td>
                  <%= link_to calltimes_path(customer.petro.id),:method => :get, :class => 'btn btn-primary' do %>
                    <i class="glyphicon glyphicon-earphone"></i>
                    <span>Gọi</span>
                  <% end %>
                  <%= link_to "Chi tiết", customer_path(customer), { :class => 'btn btn-warning' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @usually_customers %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Danh sách các khách hàng "Loại Không Thường Xuyên"</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
       Tập hợp danh sách tất cả các khách hàng <code>Không Thường Xuyên</code> của bạn, là những khách hàng có chu kì đổ nhiên liệu trong phạm vi <code>15 ngày</code>.<br>
        </p>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Tên</th>
              <th>Biển số xe</th>
              <th>SĐT</th>
              <th>Loại khách hàng</th>
              <th>Giao dịch gần nhất</th>
              <th>thuộc công ty</th>
              <th>Thực hiện cuộc gọi</th>
              <th>Tác vụ</th>
            </tr>
          </thead>

          <tbody>
            <% @rarely_customers.each do |customer| %>
              <tr>
                <td><%= customer.name %></td>
                <td><%= customer.car_number %></td>
                <td><%= customer.phone %></td>
                <td><%= customer.type_customer %></td>
                <td><%= customer.petro.day_fuel.strftime('%d/%m/%Y') %></td>
                <td><%= customer.company %></td>
                <% if customer.petro.calltimes.length > 0 %>
                  <td style="background-color: #60a917; color: white">Đã thực hiện <span><%= customer.petro.calltimes.length %></span> cuộc gọi</td>
                <% else %>
                  <td> chưa thực hiện cuộc gọi nào</td>
                <% end %>
                <td>
                  <%= link_to calltimes_path(customer.petro.id),:method => :get, :class => 'btn btn-primary' do %>
                    <i class="glyphicon glyphicon-earphone"></i>
                    <span>Gọi</span>
                  <% end %>
                  <%= link_to "Chi tiết", customer_path(customer), { :class => 'btn btn-warning' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= paginate @rarely_customers, param_name: :page_rare %>
      </div>
    </div>
  </div>
</div>