config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#new"
  get "/customers/all" => 'customers#index_all', :as => 'customers_all'
  resources :admins
  resources :customers do
    collection do
      get 'set_init_date'
    end
  end
  resources :petros
  resources :fuels
  resources :calls
  resources :employees
  resources :stations
  get "/petros/:id/calltimes" => 'calltimes#new', :as => 'calltimes'
  get "/customer/search" => 'customers#search_customer', :as => 'search_customer'
  post "/customer/search" => 'customers#search', :as => 'searched_customer'
  post "/petros/:id/calltimes" => 'calltimes#create', :as => 'create_calltimes'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/customer.rb
class Customer < ApplicationRecord
  enum type_customer: ['Thường xuyên', 'Không thường xuyên']
  has_many :petros, -> { order "day_fuel DESC" }, :dependent => :destroy
  has_many :day_fuel_petros, :dependent => :destroy, class_name: 'Petro'
  has_one :petro, -> { order "id DESC" }, class_name: 'Petro'
  accepts_nested_attributes_for :day_fuel_petros, :allow_destroy => true
  
  validates :name, 
    length: { 
      in: 4..30,
      too_short: "Tên nhập quá ngắn, phải có ít nhất 4 kí tự trở lên.",
      too_long: "Tên nhập quá dài, dưới 30 kí tự." }

  validates :phone, 
    length: { 
      in: 9..12,
      too_short: "SĐT nhập quá ngắn, phải có ít nhất 9 kí tự trở lên.",
      too_long: "SĐT nhập quá dài, dưới 12 kí tự."},
    numericality: { 
      only_integer: true,
      message: "Yêu cầu nhập các kí tự là số" }

  validates :car_number, uniqueness: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_params, only: [:edit, :show, :update, :destroy]

  def new
    @customer = Customer.new
    uri   = URI.parse(request.fullpath)
    if uri.query
      params = CGI.parse(uri.query)
      content   = params['car'].first
      @customer.car_number = content
    end
    @fuels = Fuel.all
    @petro = @customer.day_fuel_petros.build
  end

  def index_all
    # @customers = Customer.all.includes[:petro].page(params[:page]).per(100)
    if params[:start] && params[:end]
      start_date =  DateTime.parse(params[:start])
      end_date = DateTime.parse(params[:end])
      @customers =  Petro.all.where("day_fuel BETWEEN ? AND ?",start_date, end_date).group_by(&:customer)
    else
      @customers = nil
    end
  end 

  def create
    params[:customer][:day_fuel_petros_attributes]["0"][:day_fuel] = DateTime.strptime(params["day_fuel"], '%d/%m/%Y')
    fuel = Fuel.find(JSON.parse(params["type_of_fuel"])[0])
    params[:customer][:day_fuel_petros_attributes]["0"][:price_fuel] = fuel.price
    params[:customer][:day_fuel_petros_attributes]["0"][:type_fuel] = fuel.name
    params[:customer][:type_customer] = Integer(customer_params[:type_customer])
    params[:customer][:car_number] = params[:customer][:car_number].gsub(/\s+/, "").upcase
    params[:customer][:day_fuel_petros_attributes]["0"][:amount] = Float(params[:customer][:day_fuel_petros_attributes]["0"][:money])/Float(params[:customer][:day_fuel_petros_attributes]["0"][:price_fuel])
    params[:customer][:last_date_petro] = params[:customer][:day_fuel_petros_attributes]["0"][:day_fuel]
    @customer = Customer.new(customer_params)
    if @customer.save 
      flash[:success] = 'Khách hàng đã được tạo.'
      redirect_to @customer
    else
      flash[:alert] = @customer.errors.full_messages.join('  ;  ')
      redirect_to new_customer_path(car: params[:customer][:car_number])
    end
  end

  def index
    @customers = Customer.all.includes(:petros).order(last_date_petro: :desc).page(params[:page])
  end

  def show
    @petro = Petro.new
    @petros = Petro.where(customer_id: params[:id]).order(day_fuel: :desc)
    @fuels = Fuel.all
  end
  
  def edit
  end

  def update
    params[:customer][:type_customer] = Integer(customer_params[:type_customer])
    if @customer.update(customer_params)
      flash[:success] = 'Khách hàng đã được cập nhật!'
      redirect_to @customer
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    flash[:error] = 'Khách hàng đã được xóa.'
    redirect_to customers_path
  end

  def search_customer
    @customer = Customer.new
  end

  def search
    search_num = (params[:car_location] + '-' + params[:car_num]).gsub(/\s+/, "").upcase
    @customer = Customer.find_by(car_number: search_num)
    if @customer
      flash[:alert] = 'Khách hàng đã tồn tại. Đến trang thông tin khách hàng.'
      redirect_to @customer
    else
      redirect_to new_customer_path(car: search_num), notice: 'Biến số xe không tồn tại, vui lòng tạo khách hàng mới.' 
    end

  end

  def set_init_date
    Customer.all.page(params[:page]).per(params[:limit]).each do |customer|
      if customer.petros.length > 0
        customer.update(last_date_petro: customer.petros[0].day_fuel)
      end
    end
  end

  private
  def set_params
    @customer = Customer.find(params[:id])
  end

  def customer_params
  	params.require(:customer).permit(:name,:phone, :car_number, :company, :type_customer, day_fuel_petros_attributes: [:money, :amount, :type_fuel, :day_fuel, :price_fuel]) 
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Sửa thông tin khách hàng</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Khách hàng <small>thay đổi thông tin</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @customer, url: customer_path(@customer), method: 'PUT', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Họ và Tên<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :name, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">SĐT<span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :phone, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Biển số xe</label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :car_number, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Công tác tại Công ty
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                 <%= f.text_field :company, class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Loại Khách Hàng</label>
              <div class="checkbox col-md-2 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :type_customer, 0, :checked => true, class: 'flat' %> Thường xuyên
                </label>
              </div>
              <div class="checkbox col-md-3 col-sm-2 col-xs-12">
                <label>
                  <%= f.radio_button :type_customer, 1, :checked => true, class: 'flat' %> Không thường xuyên
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">Quản lý giao dịch của khách hàng này
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= link_to 'Quản lý giao dịch', customer_path(@customer),  { :class => 'btn btn-warning' } %>
              </div>
            </div>
            <div class="clearfix"></div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Hủy bỏ', customers_path,  { :class => 'btn btn-primary' } %>
                <%= link_to 'Xóa khách hàng này', customer_path(@customer), :class => 'btn btn-danger', :method => :delete, data: {:confirm => "Bạn có chắc chắn muốn xóa khách hàng này không?" } %>
                <%= f.submit 'Cập nhật', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Danh sách tổng hợp <small>tất cả khách hàng</small></h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Bảng danh sách tổng hợp</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <p class="text-muted font-13 m-b-30">
        Bảng dưới đây là tập hợp danh sách tất cả các khách hàng của bạn, bạn có thể sắp xếp danh sách theo thứ tự từng cột, bằng cách click vào cột tương ứng.<br> Ô <code>Tìm kiếm</code> năm ở góc phải màn hình giúp bạn tìm ra khách hàng cụ thể một cách nhanh nhất.
        </p>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Tên tài xế</th>
              <th>Biển số xe</th>
              <th>SĐT</th>
              <th>Ngày giao dịch gần nhất</th>
              <th>Tổng số lít (lit)</th>
              <th>Tổng số tiền</th>
              <th>Loại khách hàng</th>
              <th>Tên công ty</th>
              <th>Tác vụ</th>
            </tr>
          </thead>

          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td><%= customer.name %></td>
                <td><%= customer.car_number %></td>
                <td><%= customer.phone %></td>
                <% petros = customer.petros %>
                <% if customer.petros.length > 0 %>
                  <td><%= customer.last_date_petro.strftime('%d/%m/%Y') %></td>
                  <td><%= petros.inject(0){|sum,x| sum + x.amount }.round(2) %></td>
                  <td><%= convert_money(petros.inject(0){|sum,x| sum + x.money })%></td>
                <% else %>
                  <td></td>
                  <td></td>
                  <td></td>
                <% end %>
                <td><%= customer.type_customer %></td>
                <td><%= customer.company %></td>
                <td>
                  <%= link_to "Chi tiết", edit_customer_path(customer), { :class => 'btn btn-primary' } %>
                  <%= link_to "Thêm giao dịch", customer_path(customer), { :class => 'btn btn-warning' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index_all.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>Danh sách kết xuất <small>tất cả khách hàng</small></h3>
  </div>
</div>
<div class="clearfix"></div>
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2>Bảng danh sách tổng hợp</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Settings 1</a>
              </li>
              <li><a href="#">Settings 2</a>
              </li>
            </ul>
          </li>
          <li><a class="close-link"><i class="fa fa-close"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="row">
          <div class="col-md-4">
            <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
              <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
              <span></span> <b class="caret"></b>
            </div>
          </div>
        </div>
        <p class="text-muted font-13 m-b-30">
        Bảng dưới đây là tập hợp danh sách tất cả các khách hàng của bạn, bạn có thể sắp xếp danh sách theo thứ tự từng cột, bằng cách click vào cột tương ứng.<br> Ô <code>Tìm kiếm</code> năm ở góc phải màn hình giúp bạn tìm ra khách hàng cụ thể một cách nhanh nhất.
        </p>
        <% if @customers %>
          <table id="datatable-buttons2" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Tên tài xế</th>
                <th>Biển số xe</th>
                <th>SĐT</th>
                <th>Ngày giao dịch gần nhất</th>
                <th>Số lít (lit)</th>
                <th>Đơn giá</th>
                <th>Thành tiền</th>
                <th>Loại khách hàng</th>
                <th>Tên công ty</th>
                <th>Tác vụ</th>
              </tr>
            </thead>
            <tbody>
              <% @customers.keys.each do |customer| %>
                <% @customers[customer].each do |petro| %>
                  <tr>
                    <td><%= customer.name %></td>
                    <td><%= customer.car_number %></td>
                    <td><%= customer.phone %></td>
                    <td>
                      <%= petro.day_fuel.strftime('%d/%m/%Y')%><br>
                    </td>
                    <td>
                      <%= petro.amount%><br>
                    </td>
                    <td>
                      <%= petro.price_fuel%><br>
                    </td>
                    <td>
                      <%= petro.money%><br>
                    </td>
                    <td><%= customer.type_customer %></td>
                    <td><%= customer.company %></td>
                    <td>
                      <%= link_to "Chi tiết", edit_customer_path(customer), { :class => 'btn btn-primary' } %>
                      <%= link_to "Thêm giao dịch", customer_path(customer), { :class => 'btn btn-warning' } %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customers/search_customer.html.erb
<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Thêm hoặc Tìm Kiếm khách hàng</h3>
    </div>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Hãy nhập biển số xe<small>Hệ thống sẽ tự động đưa bạn đến form nhập thông tin nếu là khách hàng mới. Nếu Khách hàng đã tồn tại, hệ thống sẽ tìm kiếm và đưa bạn đến trang thông tin khách hàng</small></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Settings 1</a>
                </li>
                <li><a href="#">Settings 2</a>
                </li>
              </ul>
            </li>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <br />
          <%=form_for @customer, url: searched_customer_path, method: 'POST', :html => {:class => 'form-horizontal form-label-left'} do |f| %>
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Nhập biển số xe<span class="required">*</span>
              </label>
              <div class="col-md-1 col-sm-6 col-xs-12">
                <%= text_field_tag :car_location, "", class: 'form-control col-md-7 col-xs-12' %>
              </div>
              <div class="col-md-3 col-sm-6 col-xs-12">
                <%= text_field_tag :car_num, "", class: 'form-control col-md-7 col-xs-12' %>
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <%= link_to 'Hủy bỏ', customers_path,  { :class => 'btn btn-primary' } %>
                <%= f.submit 'Kiểm tra', class: 'btn btn-success'%>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/set_init_date.erb
| Success